---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Your first Network Ansible Playbook"
      solveButton: false
    - name: module-02
      label: "Validate idempotency"
      solveButton: false

tabs:
  - name: ">_Code"
    url: https://code-server-${guid}.${domain}/?folder=/home/coder/project
    external: false

  # - name: Windows RDP
  #   url: https://windows-ironrdp-${guid}.${domain}/
  #   external: false
  # - name: ">_ control"
  #   url: /wetty
  # - name: ">_ node01"
  #   url: /wetty_node01
  # - name: ">_ node02"
  #   url: /wetty_node02
  # - name: ">_ node03"
  #   url: /wetty_node03
  # - name: Cloud (PoC)
  #   url: /cloud
