---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Your first Network Ansible Playbook"
      solveButton: false
    - name: module-02
      label: "Validate idempotency"
      solveButton: false

tabs:
  - name: "VS Code"
    url: https://vscode-${guid}.${domain}/?folder=/home/coder/project
    external: false
    secondary_url: /wetty
    secondary_name: Terminal
  - name: "TERMINAL"
    url: /wetty_vscode

  # - name: Windows RDP
  #   url: https://windows-ironrdp-${guid}.${domain}/
  #   external: false
  # - name: ">_ control"
  #   url: /wetty
  # - name: ">_ node01"
  #   url: /wetty_node01
  # - name: ">_ node02"
  #   url: /wetty_node02
  # - name: ">_ node03"
  #   url: /wetty_node03
  # - name: Cloud (PoC)
  #   url: /cloud
