---
antora:
  name: modules
  dir: www
  modules:
    - name: introduction
      label: "Introduction"
      solveButton: false
    - name: module-01
      label: "Your first Network Ansible Playbook"
      solveButton: false
    - name: module-02
      label: "Validate idempotency"
      solveButton: false

tabs:
  - name: "VS Code"
    url: https://vscode-${guid}.${domain}/?folder=/home/rhel
    external: false
  - name: "TERMINAL"
    url: /wetty_vscode
